//! Endpoint detection and response.
//!
//! File integrity monitoring (with real-time notify-based watcher),
//! process tracking, indicator of compromise matching, and security
//! event generation.

pub mod watcher;

pub use watcher::{WatcherHandle, start_watcher};

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// A file integrity baseline entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileBaseline {
    pub path: PathBuf,
    pub hash: String,
    pub size: u64,
    pub modified: DateTime<Utc>,
    pub permissions: Option<String>,
}

/// A file integrity change event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimEvent {
    pub path: PathBuf,
    pub change_type: FimChangeType,
    pub old_hash: Option<String>,
    pub new_hash: Option<String>,
    pub detected_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FimChangeType {
    Created,
    Modified,
    Deleted,
    PermissionChanged,
}

/// File integrity monitor.
#[derive(Debug, Default)]
pub struct FileIntegrityMonitor {
    baseline: HashMap<PathBuf, FileBaseline>,
}

impl FileIntegrityMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a file to the baseline.
    pub fn add_baseline(&mut self, entry: FileBaseline) {
        self.baseline.insert(entry.path.clone(), entry);
    }

    /// Check a file against its baseline. Returns an event if changed.
    pub fn check_file(
        &self,
        path: &PathBuf,
        current_hash: &str,
        current_size: u64,
    ) -> Option<FimEvent> {
        match self.baseline.get(path) {
            Some(baseline) if baseline.hash != current_hash => Some(FimEvent {
                path: path.clone(),
                change_type: FimChangeType::Modified,
                old_hash: Some(baseline.hash.clone()),
                new_hash: Some(current_hash.to_string()),
                detected_at: Utc::now(),
            }),
            None => Some(FimEvent {
                path: path.clone(),
                change_type: FimChangeType::Created,
                old_hash: None,
                new_hash: Some(current_hash.to_string()),
                detected_at: Utc::now(),
            }),
            _ => None,
        }
    }

    /// Check for deleted files (in baseline but missing from current scan).
    pub fn check_deleted(&self, current_paths: &HashSet<PathBuf>) -> Vec<FimEvent> {
        self.baseline
            .keys()
            .filter(|p| !current_paths.contains(*p))
            .map(|p| FimEvent {
                path: p.clone(),
                change_type: FimChangeType::Deleted,
                old_hash: self.baseline.get(p).map(|b| b.hash.clone()),
                new_hash: None,
                detected_at: Utc::now(),
            })
            .collect()
    }

    pub fn baseline_count(&self) -> usize {
        self.baseline.len()
    }
}

/// Compute SHA-256 hash of data.
pub fn hash_data(data: &[u8]) -> String {
    format!("{:x}", Sha256::digest(data))
}

/// Indicator of Compromise (IoC) database.
#[derive(Debug, Default)]
pub struct IocDatabase {
    /// Known malicious file hashes.
    pub file_hashes: HashSet<String>,
    /// Known malicious IPs.
    pub ip_addresses: HashSet<String>,
    /// Known malicious domains.
    pub domains: HashSet<String>,
}

impl IocDatabase {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn add_hash(&mut self, hash: &str) {
        self.file_hashes.insert(hash.to_lowercase());
    }
    pub fn add_ip(&mut self, ip: &str) {
        self.ip_addresses.insert(ip.to_string());
    }
    pub fn add_domain(&mut self, domain: &str) {
        self.domains.insert(domain.to_lowercase());
    }

    pub fn check_hash(&self, hash: &str) -> bool {
        self.file_hashes.contains(&hash.to_lowercase())
    }
    pub fn check_ip(&self, ip: &str) -> bool {
        self.ip_addresses.contains(ip)
    }
    pub fn check_domain(&self, domain: &str) -> bool {
        self.domains.contains(&domain.to_lowercase())
    }

    pub fn total_indicators(&self) -> usize {
        self.file_hashes.len() + self.ip_addresses.len() + self.domains.len()
    }
}

/// A security event generated by EDR.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityEvent {
    pub event_type: SecurityEventType,
    pub severity: EventSeverity,
    pub description: String,
    pub source: String,
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub details: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SecurityEventType {
    FileIntegrityViolation,
    MaliciousHashDetected,
    SuspiciousProcess,
    UnauthorizedAdmin,
    FirewallRuleChanged,
    IoCSeen,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EventSeverity {
    Low,
    Medium,
    High,
    Critical,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fim_detects_modification() {
        let mut fim = FileIntegrityMonitor::new();
        let path = PathBuf::from("/etc/passwd");
        fim.add_baseline(FileBaseline {
            path: path.clone(),
            hash: "abc123".into(),
            size: 100,
            modified: Utc::now(),
            permissions: None,
        });

        let event = fim.check_file(&path, "different_hash", 105);
        assert!(event.is_some());
        assert_eq!(event.unwrap().change_type, FimChangeType::Modified);
    }

    #[test]
    fn fim_detects_new_file() {
        let fim = FileIntegrityMonitor::new();
        let event = fim.check_file(&PathBuf::from("/tmp/new"), "hash", 50);
        assert!(event.is_some());
        assert_eq!(event.unwrap().change_type, FimChangeType::Created);
    }

    #[test]
    fn fim_no_change() {
        let mut fim = FileIntegrityMonitor::new();
        let path = PathBuf::from("/etc/hosts");
        fim.add_baseline(FileBaseline {
            path: path.clone(),
            hash: "samehash".into(),
            size: 50,
            modified: Utc::now(),
            permissions: None,
        });
        assert!(fim.check_file(&path, "samehash", 50).is_none());
    }

    #[test]
    fn fim_detects_deleted() {
        let mut fim = FileIntegrityMonitor::new();
        fim.add_baseline(FileBaseline {
            path: PathBuf::from("/etc/shadow"),
            hash: "h".into(),
            size: 10,
            modified: Utc::now(),
            permissions: None,
        });
        let current: HashSet<PathBuf> = HashSet::new(); // empty = all deleted
        let events = fim.check_deleted(&current);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].change_type, FimChangeType::Deleted);
    }

    #[test]
    fn ioc_matching() {
        let mut db = IocDatabase::new();
        db.add_hash("abc123");
        db.add_ip("10.0.0.1");
        db.add_domain("evil.com");

        assert!(db.check_hash("ABC123")); // case insensitive
        assert!(db.check_ip("10.0.0.1"));
        assert!(db.check_domain("EVIL.COM"));
        assert!(!db.check_hash("clean"));
        assert_eq!(db.total_indicators(), 3);
    }

    #[test]
    fn hash_data_deterministic() {
        let h1 = hash_data(b"test");
        let h2 = hash_data(b"test");
        assert_eq!(h1, h2);
        assert_ne!(h1, hash_data(b"other"));
    }

    #[test]
    fn security_event_serialization() {
        let event = SecurityEvent {
            event_type: SecurityEventType::MaliciousHashDetected,
            severity: EventSeverity::Critical,
            description: "Known malware detected".into(),
            source: "fim".into(),
            timestamp: Utc::now(),
            details: serde_json::json!({"file": "/tmp/bad.exe", "hash": "abc"}),
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: SecurityEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.event_type, SecurityEventType::MaliciousHashDetected);
    }
}
